apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: app
  newName: ogabrielpereiraa/prova-devops
  newTag: latest
- name: prova-devops
  newName: ogabrielpereiraa/prova-devops
  newTag: ecb1ce7cda8792f5b2b4d04c92626c21f53ebc4e
